version: "3.8"

services:
  postgres_16.3:
    image: postgres:16.3
    environment:
      POSTGRES_DB: cocolabhub
      POSTGRES_USER: cocolabhub
      POSTGRES_PASSWORD: cocolabhub
    ports:
      - "5432:5432"
  springboot3_react18:
    image: ${IMAGE_NAME}
    build:
      context: .
      args:
        APP_DIR_NAME: ${APP_DIR_NAME}
        GIT_URI: ${GIT_URI}
        GIT_BRANCH_NAME: ${GIT_BRANCH_NAME}
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - "8080:8080"
      - "3000:3000"
