package com.user.IntArea.entity.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum QuotationProgress {

    // 판매자의 견적서 작성 단계
    SELLER_CREATED_AND_PENDING("SELLER_CREATED_AND_PENDING"), // 판매자가 견적서 작성 후 고객의 응답을 기다림
    SELLER_CANCELLED("SELLER_CANCELLED"), // 판매자 거래 취소(견적서 작성 거부)
    SELLER_UPDATED_FORMER_QUOTATION_REMAINS_AS_RECORD("SELLER_UPDATED_FORMER_QUOTATION_REMAINS_AS_RECORD"), // 내용을 업데이트하면 이전의 견적서는 기록으로만 남음
    SELLER_UPDATED_AND_PENDING("SELLER_UPDATED_AND_PENDING"), // 판매자가 새로운 견적서 작성 후 고객의 응답을 기다림

    // 고객 선택 단계
    CUSTOMER_ASKED_REVISE("CUSTOMER_ASKED_REVISE"), // 고객이 견적서 수정을 요청
    CUSTOMER_CANCELLED("CUSTOMER_CANCELLED"), // 고객 견적서 거절
    CUSTOMER_APPROVED("CUSTOMER_APPROVED"), // 고객 견적서 승인

    // 고객 결제 단계
    CUSTOMER_PAID("CUSTOMER_PAID"), // 고객 견적서에 대해 비용 지불

    // 서비스 시작 전
    SELLER_SERVICE_PENDING("SELLER_SERVICE_PENDING"), // 고객 결제 후 판매자 서비스 시작 전
    SELLER_SERVICE_CANCELLED_REFUND_NECESSARY("SELLER_SERVICE_CANCELLED_REFUND_NECESSARY"), // 판매자의 서비스 불가로 환불 필요

    // 판매자 서비스 진행 중
    SELLER_SERVICE_IN_PROGRESS("SELLER_SERVICE_IN_PROGRESS"), // 서비스 시작 및 진행중

    // (예외) 판매자의 서비스 시작 이후 서비스 중지
    SELLER_SERVICE_CEASED_BY_CUSTOMER_REQUEST("SELLER_SERVICE_CEASED_BY_ACCIDENT"), // 고객의 중지 요청
    SELLER_SERVICE_CEASED_BY_DISASTER("SELLER_SERVICE_CEASED_BY_DISASTER"), // 천재지변, 전쟁, 사변 등
    SELLER_SERVICE_CEASED_BY_SELLER_SHUTDOWN("SELLER_SERVICE_CEASED_BY_SELLER_SHUTDOWN"), // 판매자 폐업
    SELLER_SERVICE_CEASED_BY_SELLER_PROBLEM("SELLER_SERVICE_CEASED_BY_SELLER_PROBLEM"), // 판매자 귀책사유
    SELLER_SERVICE_CEASED_BY_OTHER_REASON("SELLER_SERVICE_CEASED_BY_OTHER_REASON"), // 기타 사유

    // 판매자의 서비스 완료 처리 => 고객의 확인 이후 계약 종료 단계로 변경
    SELLER_SERVICE_COMPLETED("SELLER_SERVICE_COMPLETED"),

    // 고객의 확인 단계
    CUSTOMER_APPROVED_SELLER_SERVICE("CUSTOMER_APPROVED_SELLER_SERVICE"),
    CUSTOMER_DISAPPROVED_SELLER_SERVICE("CUSTOMER_DISAPPROVED_SELLER_SERVICE"),

    // (예외) 부분 또는 전체 환불 필요
    CUSTOMER_APPROVED_SELLER_SERVICE_AND_REQUEST_REFUND("CUSTOMER_APPROVED_SELLER_SERVICE_AND_REQUEST_REFUND"),
    CUSTOMER_DISAPPROVED_SELLER_SERVICE_AND_REQUEST_REFUND("CUSTOMER_DISAPPROVED_SELLER_SERVICE_AND_REQUEST_REFUND"),


    // 아래의 계약 종료 단계는 모든 환불 조치를 포함하여 모든 의무 이행이 완료되고 더 이상 시스템상으로 조치할 사항이 없을 경우에만 적용

    // 계약 종료 단계(서비스 이행 완료)
    CONTRACT_COMPLETED_WITH_ORIGINAL_CONTRACT("CONTRACT_COMPLETED_WITH_ORIGINAL_CONTRACT"),
    CONTRACT_COMPLETED_WITH_PARTIAL_REFUND("CONTRACT_COMPLETED_WITH_PARTIAL_REFUND"),
    CONTRACT_COMPLETED_WITH_INCREASED_COST("CONTRACT_COMPLETED_WITH_INCREASED_COST"),

    // 계약 종료 단계(서비스 불이행)
    CONTRACT_TERMINATED_WITH_CANCEL("CONTRACT_TERMINATED_WITH_CANCEL"),
    CONTRACT_TERMINATED_WITH_REFUND("CONTRACT_TERMINATED_WITH_REFUND"),
    CONTRACT_TERMINATED_WITH_PARTIAL_REFUND("CONTRACT_TERMINATED_WITH_PARTIAL_REFUND");

    private final String progress;
}
