package com.user.IntArea.entity.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum QuotationProgress {

    // 견적서 작성 후 고객 응답 대기 단계
    PENDING("PENDING"),
    SELLER_CANCELLED("SELLER_CANCELLED"),
    SELLER_MODIFIED_TO_NEW_QUOTATION("SELLER_MODIFIED_TO_NEW_QUOTATION"),

    // 고객 선택 단계
    CUSTOMER_REJECTED("CUSTOMER_REJECTED"),
    CUSTOMER_APPROVED("CUSTOMER_APPROVED"),
    CUSTOMER_PAID("CUSTOMER_PAID"),

    // 서비스 이행 단계
    SELLER_SERVICE_PENDING("SELLER_SERVICE_PENDING"),
    SELLER_SERVICE_UNABLE_REFUND_NECESSARY("SELLER_SERVICE_UNABLE_REFUND_NECESSARY"),
    SELLER_SERVICE_IN_PROGRESS("SELLER_SERVICE_IN_PROGRESS"),
    SELLER_SERVICE_CEASED_BY_SHUTDOWN("SELLER_SERVICE_CEASED_BY_SHUTDOWN"),
    SELLER_SERVICE_CEASED_BY_ACCIDENT("SELLER_SERVICE_CEASED_BY_ACCIDENT"),
    SELLER_SERVICE_CEASED_BY_CUSTOMER_REQUEST("SELLER_SERVICE_CEASED_BY_ACCIDENT"),
    SELLER_SERVICE_COMPLETED("SELLER_SERVICE_COMPLETED"),

    // 계약 완료단계
    CONTRACT_COMPLETED_WITH_ORIGINAL_CONTRACT("CONTRACT_COMPLETED_WITH_ORIGINAL_CONTRACT"),
    CONTRACT_COMPLETED_WITH_PARTIAL_REFUND("CONTRACT_COMPLETED_WITH_PARTIAL_REFUND"),
    CONTRACT_COMPLETED_WITH_INCREASED_COST("CONTRACT_COMPLETED_WITH_INCREASED_COST"),
    CONTRACT_TERMINATED_WITH_REFUND("CONTRACT_TERMINATED_WITH_REFUND");

    private final String progress;
}
