package com.user.IntArea.entity.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum QuotationProgress {

    // 판매자가 견적서 작성 후 고객의 응답을 대기하는 단계
    PENDING("PENDING"),
    SELLER_CANCELLED("SELLER_CANCELLED"),
    SELLER_UPDATED_TO_NEW_QUOTATION("SELLER_UPDATED_TO_NEW_QUOTATION"),

    // 고객 선택 단계
    CUSTOMER_REJECTED("CUSTOMER_REJECTED"),
    CUSTOMER_APPROVED("CUSTOMER_APPROVED"),
    CUSTOMER_PAID("CUSTOMER_PAID"),

    // 서비스 이행 단계
    SELLER_SERVICE_PENDING("SELLER_SERVICE_PENDING"),
    SELLER_SERVICE_UNABLE_REFUND_NECESSARY("SELLER_SERVICE_UNABLE_REFUND_NECESSARY"),
    SELLER_SERVICE_IN_PROGRESS("SELLER_SERVICE_IN_PROGRESS"),
    SELLER_SERVICE_CEASED_BY_DISASTER("SELLER_SERVICE_CEASED_BY_DISASTER"), // 천재지변, 전쟁, 사변 등
    SELLER_SERVICE_CEASED_BY_SELLER_SHUTDOWN("SELLER_SERVICE_CEASED_BY_SELLER_SHUTDOWN"), // 판매자 폐업
    SELLER_SERVICE_CEASED_BY_SELLER_PROBLEM("SELLER_SERVICE_CEASED_BY_SELLER_PROBLEM"), // 판매자 사정
    SELLER_SERVICE_CEASED_BY_CUSTOMER_REQUEST("SELLER_SERVICE_CEASED_BY_ACCIDENT"), // 고객의 중지 요청
    SELLER_SERVICE_CEASED_BY_OTHER_REASON("SELLER_SERVICE_CEASED_BY_OTHER_REASON"), // 기타 사유
    SELLER_SERVICE_COMPLETED("SELLER_SERVICE_COMPLETED"),

    // 계약 완료단계
    CONTRACT_COMPLETED_WITH_ORIGINAL_CONTRACT("CONTRACT_COMPLETED_WITH_ORIGINAL_CONTRACT"),
    CONTRACT_COMPLETED_WITH_PARTIAL_REFUND("CONTRACT_COMPLETED_WITH_PARTIAL_REFUND"),
    CONTRACT_COMPLETED_WITH_INCREASED_COST("CONTRACT_COMPLETED_WITH_INCREASED_COST"),
    CONTRACT_TERMINATED_WITH_REFUND("CONTRACT_TERMINATED_WITH_REFUND");

    private final String progress;
}
